targetScope = 'resourceGroup'

// ─── Parameters ───────────────────────────────────────────────────────────────

@description('Deployment stage')
@allowed(['dev', 'prod'])
param stage string

@description('Primary Azure region')
param location string

@description('Photos CDN custom domain (e.g. cdn.dev.clos-bon-accueil.fr)')
param cdnDomain string

@description('Enable Cosmos DB continuous backup (PITR) — requires autoscale throughput')
param enablePointInTimeRecovery bool

@description('Cosmos DB max autoscale throughput (RU/s)')
param cosmosMaxThroughput int

@description('Allowed CORS origins for Blob Storage PUT (photo upload via SAS token)')
param allowedOrigins array

@description('App Configuration store name (for writing runtime config entries)')
param appConfigName string

@description('Key Vault name (referenced in App Config for secrets)')
param keyVaultName string

// ─── App Configuration reference ─────────────────────────────────────────────

resource appConfig 'Microsoft.AppConfiguration/configurationStores@2023-03-01' existing = {
  name: appConfigName
}

// ─── Cosmos DB ────────────────────────────────────────────────────────────────
// Single-container design: one database + one container, partition key /pk.
// Automatic indexing covers all properties (no explicit GSIs needed, unlike DynamoDB).
// TTL enabled at container level (defaultTtl: -1) — per-item ttl field controls expiry.
// Idempotency records use 24h TTL; all other items have no expiry.

resource cosmosAccount 'Microsoft.DocumentDB/databaseAccounts@2024-02-15-preview' = {
  name: 'clos-cosmos-${stage}'
  location: location
  kind: 'GlobalDocumentDB'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    databaseAccountOfferType: 'Standard'
    locations: [
      {
        locationName: location
        failoverPriority: 0
        isZoneRedundant: false
      }
    ]
    consistencyPolicy: {
      defaultConsistencyLevel: 'Session'
    }
    enableAutomaticFailover: false
    enableMultipleWriteLocations: false
    disableLocalAuth: false
    backupPolicy: enablePointInTimeRecovery ? {
      type: 'Continuous'
      continuousModeProperties: {
        tier: 'Continuous7Days'
      }
    } : {
      type: 'Periodic'
      periodicModeProperties: {
        backupIntervalInMinutes: 240
        backupRetentionIntervalInHours: 8
        backupStorageRedundancy: 'Local'
      }
    }
    capabilities: []
    networkAclBypass: 'AzureServices'
  }
}

resource cosmosDatabase 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases@2024-02-15-preview' = {
  name: 'clos-bon-accueil'
  parent: cosmosAccount
  properties: {
    resource: {
      id: 'clos-bon-accueil'
    }
  }
}

resource cosmosContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-02-15-preview' = {
  name: 'main'
  parent: cosmosDatabase
  properties: {
    resource: {
      id: 'main'
      partitionKey: {
        paths: ['/pk']
        kind: 'Hash'
        version: 2
      }
      defaultTtl: -1
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: [
          { path: '/_etag/?' }
        ]
      }
    }
    options: {
      autoscaleSettings: {
        maxThroughput: cosmosMaxThroughput
      }
    }
  }
}

// ─── Blob Storage ─────────────────────────────────────────────────────────────
// Storage account name: lowercase alphanumeric, 3-24 chars (globally unique).
// Two containers:
//   - photos: private, accessed via SAS tokens generated by clos-api (PM4/PM6)
//   - $web:   static website hosting for the SPA (Azure CDN serves from here in PM6)

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: 'closstorage${stage}'
  location: location
  kind: 'StorageV2'
  sku: {
    name: stage == 'prod' ? 'Standard_GRS' : 'Standard_LRS'
  }
  properties: {
    accessTier: 'Hot'
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: true
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
    }
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  name: 'default'
  parent: storageAccount
  properties: {
    isVersioningEnabled: stage == 'prod'
    cors: {
      corsRules: [
        {
          allowedOrigins: allowedOrigins
          allowedMethods: ['PUT']
          allowedHeaders: ['Content-Type', 'x-ms-blob-type', 'x-ms-blob-content-type']
          exposedHeaders: []
          maxAgeInSeconds: 3000
        }
      ]
    }
    deleteRetentionPolicy: {
      enabled: stage == 'prod'
      days: stage == 'prod' ? 7 : 1
    }
    staticWebsite: {
      enabled: true
      indexDocument: 'index.html'
      errorDocument404Path: 'index.html'
    }
  }
}

resource photosContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  name: 'photos'
  parent: blobService
  properties: {
    publicAccess: 'None'
  }
}

resource webContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  name: '$web'
  parent: blobService
  properties: {
    publicAccess: 'None'
  }
}

// ─── Azure CDN ────────────────────────────────────────────────────────────────
// Standard_Microsoft CDN profile with two endpoints:
//   - clos-cdn-photos-{stage}: serves room photos from the "photos" container
//   - clos-cdn-web-{stage}:    serves the SPA from the "$web" container
// Custom domains and TLS certificates are configured post-deployment via:
//   az cdn custom-domain create --resource-group rg-clos-bon-accueil-{stage} ...
// Azure CDN Standard from Microsoft handles TLS cert rotation automatically.

resource cdnProfile 'Microsoft.Cdn/profiles@2023-05-01' = {
  name: 'clos-cdn-${stage}'
  location: 'global'
  sku: {
    name: 'Standard_Microsoft'
  }
}

resource cdnEndpointPhotos 'Microsoft.Cdn/profiles/endpoints@2023-05-01' = {
  name: 'clos-cdn-photos-${stage}'
  parent: cdnProfile
  location: 'global'
  properties: {
    originHostHeader: '${storageAccount.name}.blob.core.windows.net'
    isHttpAllowed: false
    isHttpsAllowed: true
    queryStringCachingBehavior: 'IgnoreQueryString'
    optimizationType: 'GeneralMediaStreaming'
    origins: [
      {
        name: 'blob-origin'
        properties: {
          hostName: '${storageAccount.name}.blob.core.windows.net'
          httpsPort: 443
          originHostHeader: '${storageAccount.name}.blob.core.windows.net'
        }
      }
    ]
    deliveryPolicy: {
      rules: [
        {
          name: 'EnforceHTTPS'
          order: 1
          conditions: [
            {
              name: 'RequestScheme'
              parameters: {
                typeName: 'DeliveryRuleRequestSchemeConditionParameters'
                operator: 'Equal'
                matchValues: ['HTTP']
                negateCondition: false
                transforms: []
              }
            }
          ]
          actions: [
            {
              name: 'UrlRedirect'
              parameters: {
                typeName: 'DeliveryRuleUrlRedirectActionParameters'
                redirectType: 'Moved'
                destinationProtocol: 'Https'
              }
            }
          ]
        }
      ]
    }
  }
}

resource cdnEndpointWeb 'Microsoft.Cdn/profiles/endpoints@2023-05-01' = {
  name: 'clos-cdn-web-${stage}'
  parent: cdnProfile
  location: 'global'
  properties: {
    originHostHeader: '${storageAccount.name}.z28.web.core.windows.net'
    isHttpAllowed: false
    isHttpsAllowed: true
    queryStringCachingBehavior: 'IgnoreQueryString'
    optimizationType: 'GeneralWebDelivery'
    origins: [
      {
        name: 'static-web-origin'
        properties: {
          hostName: '${storageAccount.name}.z28.web.core.windows.net'
          httpsPort: 443
          originHostHeader: '${storageAccount.name}.z28.web.core.windows.net'
        }
      }
    ]
    deliveryPolicy: {
      rules: [
        {
          name: 'EnforceHTTPS'
          order: 1
          conditions: [
            {
              name: 'RequestScheme'
              parameters: {
                typeName: 'DeliveryRuleRequestSchemeConditionParameters'
                operator: 'Equal'
                matchValues: ['HTTP']
                negateCondition: false
                transforms: []
              }
            }
          ]
          actions: [
            {
              name: 'UrlRedirect'
              parameters: {
                typeName: 'DeliveryRuleUrlRedirectActionParameters'
                redirectType: 'Moved'
                destinationProtocol: 'Https'
              }
            }
          ]
        }
        {
          name: 'SpaFallback'
          order: 2
          conditions: [
            {
              name: 'UrlFileExtension'
              parameters: {
                typeName: 'DeliveryRuleUrlFileExtensionMatchConditionParameters'
                operator: 'LessThan'
                negateCondition: false
                matchValues: ['1']
                transforms: []
              }
            }
          ]
          actions: [
            {
              name: 'UrlRewrite'
              parameters: {
                typeName: 'DeliveryRuleUrlRewriteActionParameters'
                sourcePattern: '/'
                destination: '/index.html'
                preserveUnmatchedPath: false
              }
            }
          ]
        }
      ]
    }
  }
}

// ─── App Configuration entries ────────────────────────────────────────────────

resource configCosmosEndpoint 'Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01' = {
  name: 'clos-${stage}-data-cosmos-endpoint'
  parent: appConfig
  properties: {
    value: cosmosAccount.properties.documentEndpoint
    contentType: 'text/plain'
  }
}

resource configCosmosDatabase 'Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01' = {
  name: 'clos-${stage}-data-cosmos-database'
  parent: appConfig
  properties: {
    value: cosmosDatabase.name
    contentType: 'text/plain'
  }
}

resource configCosmosContainer 'Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01' = {
  name: 'clos-${stage}-data-cosmos-container'
  parent: appConfig
  properties: {
    value: cosmosContainer.name
    contentType: 'text/plain'
  }
}

resource configStorageAccount 'Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01' = {
  name: 'clos-${stage}-data-storage-account'
  parent: appConfig
  properties: {
    value: storageAccount.name
    contentType: 'text/plain'
  }
}

resource configPhotosContainer 'Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01' = {
  name: 'clos-${stage}-data-photos-container'
  parent: appConfig
  properties: {
    value: photosContainer.name
    contentType: 'text/plain'
  }
}

resource configCdnPhotosDomain 'Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01' = {
  name: 'clos-${stage}-data-cdn-photos-domain'
  parent: appConfig
  properties: {
    value: cdnDomain
    contentType: 'text/plain'
  }
}

resource configCdnWebDomain 'Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01' = {
  name: 'clos-${stage}-data-cdn-web-domain'
  parent: appConfig
  properties: {
    value: cdnEndpointWeb.properties.hostName
    contentType: 'text/plain'
  }
}

// ─── Outputs ──────────────────────────────────────────────────────────────────

output cosmosAccountName string = cosmosAccount.name
output storageAccountName string = storageAccount.name
output storageBlobEndpoint string = storageAccount.properties.primaryEndpoints.blob
output cdnPhotosDomain string = cdnEndpointPhotos.properties.hostName
output cdnWebDomain string = cdnEndpointWeb.properties.hostName
