version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      azure-sdk:
        patterns:
          - "@azure/*"
      testing:
        patterns:
          - "@playwright/test"
          - "vitest"
          - "@testing-library/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
